Add metadata column to SQLiteYStore, fix update broadcast
y-crdt/ypy-websocket pull request #42
Opened 2022-11-16 11:53 UTC by davidbrochart

2022-11-16 13:51 UTC, fcollonval requested changes

2022-11-16 13:51 UTC, fcollonval commented on ypy_websocket/websocket_server.py
> +                self.log.debug("... to client with endpoint: %s", client.path)
Could you keep a single call because log handler are expecting that - as well as sys admin monitoring deployed application.

2022-11-16 13:51 UTC, fcollonval commented on ypy_websocket/websocket_server.py
> +            self.ydoc._ready = True
Calling a protected variable is a bad practice.

2022-11-16 13:51 UTC, fcollonval commented on ypy_websocket/websocket_server.py
> +        self.ydoc.init(self._update_queue)  # FIXME: overriding Y.YDoc.__init__ doesn't seem to work
I guess overriding is not working as the class is implemented in Rust.

2022-11-16 13:51 UTC, fcollonval commented on ypy_websocket/ydoc.py
> +class YDoc(Y.YDoc):
Could you elaborate on the problem solved by theses classes? Usually (I have experience with C/C++ but not Rust binding) overriding compiled classes by pure Python implementation highly impacts the code speed.

2022-11-16 14:32 UTC, davidbrochart commented on ypy_websocket/websocket_server.py
> +        self.ydoc.init(self._update_queue)  # FIXME: overriding Y.YDoc.__init__ doesn't seem to work
No, that was fixed in https://github.com/y-crdt/ypy/pull/39 and I can see it works fine on a simple example, but strangely, not here.

2022-11-16 14:35 UTC, davidbrochart commented on ypy_websocket/ydoc.py
> +class YDoc(Y.YDoc):
As said in the docstring bellow, we need to watch updates made to the internal YDoc by the backend only, not the external clients.
`Y.YDoc.observe_after_transaction` would watch everything.

2022-11-16 14:36 UTC, davidbrochart commented on ypy_websocket/websocket_server.py
> +                self.log.debug("... to client with endpoint: %s", client.path)
Will do, but this will probably print a long line.

2022-11-16 16:14 UTC, fcollonval commented on ypy_websocket/websocket_server.py
> +        self.ydoc.init(self._update_queue)  # FIXME: overriding Y.YDoc.__init__ doesn't seem to work
Here are an interesting discussion on PyO3: https://github.com/PyO3/pyo3/issues/1644

2022-11-17 10:18 UTC, davidbrochart commented
I think [tests fail](https://github.com/y-crdt/ypy-websocket/actions/runs/3486854815/jobs/5833807123) because of https://github.com/y-crdt/ypy/issues/94.

2022-11-17 10:29 UTC, davidbrochart commented
> I think [tests fail](https://github.com/y-crdt/ypy-websocket/actions/runs/3486854815/jobs/5833807123) because of [y-crdt/ypy#94](https://github.com/y-crdt/ypy/issues/94).

My bad, fixed in https://github.com/y-crdt/ypy-websocket/pull/42/commits/3b57fbcc218a07bc10e66fe64a6b518145ff8b3a.

2022-11-17 10:39 UTC, merged